account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('admin/dashboard/', views.admin_dashboard_view, name='admin_dashboard'),
    path('register/', views.register_view, name='register'),
]

frontend/urls.py
from django.urls import path

from . import views

app_name = 'frontend'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('get-quote-now/', views.frontend_get_quote, name='frontend_get_quote'),
]

insurigo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('account/', include('account.urls', namespace='account')),
    path('account/user/', include('customer.urls', namespace='customer')),
    path('account/car-insurance/', include('car_insurance.urls', namespace='car_insurance')),
    path('account/payments/', include('payments.urls', namespace='payments')),
    path('account/health_insurance/', include('health_insurance.urls', namespace='health_insurance')),
    path('account/claims/', include('claims.urls', namespace='claims')),
    path('api/', include('quote.urls', namespace='quote')),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quote/urls.py
from django.urls import path
from .views import ping_supabase

app_name = 'quote'

urlpatterns = [
    path('ping/', ping_supabase),
]

frontend/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

def home(request):
    return render(request, 'frontend/index.html')

def frontend_get_quote(request):
    if request.method == 'POST':
        messages.error(request, 'You need to register with us to be able to access the quote engine, Register with the form below. Registration is free')
        return redirect('account:register')
    pass

def about(request):
    return render(request, 'frontend/about.html')

def services(request):
    return render(request, 'frontend/services.html')

templates/frontend/included/footer.html
{% load static %}
<!-- ==== Footer Section Start ==== -->
<footer class="rs-footer pt-100 pb-70">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="rs-footer__about">
                    <a href="{% url 'frontend:home' %}"><img src="{% static 'frontend/assets/images/logo_light.png' %}" alt=""></a>
                    <p class="desc">Protect What Matters Most — Easy Car & Health Insurance You Can Trust. We're here to help you and your business manage risks and keep your financial future secure—without any extra costs or surprises.</p>
                    <!-- <ul>
                        <li><a href="#"><i class="ri-facebook-fill"></i></a></li>
                        <li><a href="#"><i class="ri-twitter-x-fill"></i></a></li>
                        <li><a href="#"><i class="ri-linkedin-fill"></i></a></li>
                        <li><a href="#"><i class="ri-instagram-line"></i></a></li>
                    </ul> -->
                </div>
            </div>
            <div class="col-lg-2 col-md-6">
                <div class="rs-footer__navigation">
                    <h4 class="title">Quick link</h4>
                    <ul>
                        <li><a href="#">About Us <i class="ri-arrow-right-line"></i></a></li>
                        <li><a href="#">Get a Qoute<i class="ri-arrow-right-line"></i></a></li>
                        <li><a href="#">Our Mission <i class="ri-arrow-right-line"></i></a></li>
                        <li><a href="#">Latest News <i class="ri-arrow-right-line"></i></a></li>
                        <li><a href="#">Contact Us <i class="ri-arrow-right-line"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="rs-footer__navigation item-2">
                    <h4 class="title">Our Services</h4>
                    <ul>
                        <li><a href="#">Travel Insurance <i class="ri-arrow-right-line"></i></a></li>
                        <li><a href="#">Life Insurance <i class="ri-arrow-right-line"></i></a></li>
                        <li><a href="#">House Insurance <i class="ri-arrow-right-line"></i></a></li>
                        <li><a href="#">Car Insurance <i class="ri-arrow-right-line"></i></a></li>
                        <li><a href="#">Health Insurance <i class="ri-arrow-right-line"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="rs-footer__contact">
                    <h4 class="title">Get In Touch</h4>
                    <ul>
                        <li>
                            <div class="rs-icon">
                                <i class="ri-map-2-line"></i>
                            </div>
                            <span>374 William S Canning Blvd, Fall River MA 2721, USA </span>
                        </li>
                        <li>
                            <div class="rs-icon">
                                <i class="ri-phone-line"></i>
                            </div>
                            <a href="tel:+880155-69569">(+880)155-69569</a>
                        </li>
                        <li>
                            <div class="rs-icon">
                                <i class="ri-mail-send-line"></i>
                            </div>
                            <a href="mailto:isurigo@gmail">support@insurigorex.org</a>
                        </li>
                        <li>
                            <div class="rs-icon">
                                <i class="ri-corner-down-right-line"></i>
                            </div>
                            <a href="">More Information</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="rs-footer__bottom">
                    <div class="row align-items-center">
                        <div class="col-lg-6">
                            <div class="rs-footer__copyright-text">
                                <p>© 2025 insurigorex.</p>
                                <!-- <p>© 2024 Insurigo. Designed By <a href="https://rstheme.com" target="_blank">RSTheme.</a></p> -->
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="rs-footer__bottom-link">
                                <ul>
                                    <li><a href="#">Sitemap</a></li>
                                    <li><a href="#">Privacy Policy</a></li>
                                    <li><a href="#">Terms of use</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- ==== Footer Section Ends ==== -->

templates/frontend/included/navbar.html
{% load static %}
<!-- ==== Header Section Start ==== -->
<header class="rs-header">
  <div class="rs-header__topbar">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-7">
          <div class="rs-header__info">
            <ul>
              <li>
                <div class="icon"><i class="ri-map-pin-2-line"></i></div>
                2972 Westheimer 96 Road 1734.
              </li>
              <li>
                <div class="icon"><i class="ri-time-line"></i></div>
                Opening Hours: 8:00am - 07:00pm
              </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-5">
          <div class="rs-header__top-rightbar">
            <div class="rs-header__info item-2">
              <ul>
                <li>
                  <a href="mailto:info@example.com">
                    <div class="icon"><i class="ri-mail-send-line"></i></div>
                    support@insurigorex.org
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="rs-header__main-box">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <div class="rs-header__main">
            <div class="rs-logo-area">
              <a href="index.html"
                ><img src="{% static 'frontend/assets/images/logo-1.png' %}" alt=""
              /></a>
            </div>
            <div class="rs-header-rightside">
              <div class="main-menu hidden-md">
                <ul class="nav-menu">
                  <li class="has-clid relative">
                    <a href="{% url 'frontend:home' %}" class="active"
                      >Home</a>
                  </li>
                  <li class="has-clid relative">
                    <a href="{% url 'frontend:about' %}"
                      >About Us </a>
                  </li>
                  <li class="has-clid relative">
                    <a href="{% url 'frontend:services' %}"
                      >Services</a>
                  </li>
                  <li><a href="contact.html">Contact Us</a></li>
                  <li><a href="{% url 'account:login' %}">Login</a></li>
                  <li><a href="{% url 'account:register' %}">Register</a></li>
                </ul>
                <!-- //.nav-menu -->
              </div>
              <div class="rs-header-contact">
                <a href="tel:+009800780423">
                  <div class="rs-icon"><i class="ri-phone-line"></i></div>
                  <div class="rs-content">
                    <span>Free Consultant</span>
                    <h4 class="title">+00 9800 7804 23</h4>
                  </div>
                </a>
              </div>
              <div class="rs-header-btn ml-35">
                <a class="main-btn" href="contact.html"
                  >Track Your Claim <i class="ri-arrow-right-line"></i
                ></a>
              </div>
              <div class="rs-header-toggle off-canver-menu">
                <span class="black"></span>
                <span></span>
                <span class="black"></span>
                <span></span>
                <span class="black"></span>
                <span></span>
                <span class="black"></span>
                <span></span>
                <span class="black"></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- ==== Header Section Ends ==== -->



<!--===== OFF CANVAS WRAP Start =====-->
<div class="off-canvas-wrap">
    <div class="overly"></div>
    <div class="off-canvas-widget">
        <a href="#" class="off-canvas-close"><i class="ri-close-line"></i></a>
        <div class="widget about-widget">
            <a href="index.html"><img src="{% static 'frontend/assets/images/logo-1.png' %}" alt=""></a>
            <p class="mt-20 mb-20">We provide insurance for nearly anything that moves you. Whether you're cruising down the road, exploring rugged trails, or navigating the open water, we're here to help you find the perfect coverage for your vehicle.</p>
        </div>
        <div class="off-canvas-menu">
            <ul class="nav-menu">
                <li>
                    <a href="{% url 'frontend:home' %}">Home</a>
                </li>
                <!-- <li>
                    <a href="{% url 'frontend:home' %}">Home</a>
                </li> -->
                <li>
                    <a href="{% url 'frontend:about' %}">About</a>
                </li>
                <li>
                    <a href="{% url 'frontend:services' %}">Services</a>
                </li>
                <li><a href="contact.html">Contact Us</a></li>
                <li>
                    <a href="{% url 'account:login' %}">Login</a>
                </li>
                <li>
                    <a href="{% url 'account:register' %}">Register</a>
                </li>
                
                
            </ul> <!-- //.nav-menu -->
        </div>
        <div class="widget gallery-widget">
            <div class="rs-gallery-item">
                <img src="{% static 'frontend/assets/images/galley-thumb-1.jpg' %}" alt="">
            </div>
            <div class="rs-gallery-item">
                <img src="{% static 'frontend/assets/images/galley-thumb-2.jpg' %}" alt="">
            </div>
            <div class="rs-gallery-item">
                <img src="{% static 'frontend/assets/images/galley-thumb-3.jpg' %}" alt="">
            </div>
            <div class="rs-gallery-item">
                <img src="{% static 'frontend/assets/images/galley-thumb-4.jpg' %}" alt="">
            </div>
            <div class="rs-gallery-item">
                <img src="{% static 'frontend/assets/images/galley-thumb-5.jpg' %}" alt="">
            </div>
            <div class="rs-gallery-item">
                <img src="{% static 'frontend/assets/images/galley-thumb-6.jpg' %}" alt="">
            </div>
        </div>
        <div class="widget contact-widget">
            <ul>
                <li>
                    <i class="ri-map-pin-2-line"></i>
                    305 Royal Track Suite 019, USA
                </li>
                <li>
                    <i class="ri-phone-line"></i>
                    <a href="tel:+10910910920">+10910-910920</a>
                </li>
                <li>
                    <i class="ri-mail-send-line"></i>
                    <a href="mailto:info@company.com">support@insurigorex.org</a>
                </li>
                <li>
                    <i class="ri-time-line"></i>
                    09:00 - 19:00
                </li>
            </ul>
        </div>
        
    </div>
</div>
<!--===== OFF CANVAS WRAP Ends =====-->